!jmb-configuration-v1

name: JMB1
outboundEndpoints:
- name: HOST
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-HOST"
- name: TMA
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-TMA"
- name: WMA
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-WMA"
- name: OMS
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-OMS"
outboundMappings:
  - receiver: 'HOST.GLOBAL'
    request: '*:*:*'
    outboundEndpoint: 'HOST'
  - receiver: 'TMS.GLOBAL'
    request: '*:*:*'
    outboundEndpoint: 'TMA'
  - receiver: 'WMA.WEST|WMA.EAST'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.DC0001'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.V0001'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.V0002'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.DICKS'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.CAR-CON3'
    request: '*:*:*'
    outboundEndpoint: 'WMA'    
  - receiver: 'LOC.DC0002'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.DC1001'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.DC1002'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.DC1003'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.E1200'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.CAR-CON3'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.DC1004'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.DC1005'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'LOC.DC1006'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'OMS.GLOBAL'
    request: '*:*:*'
    outboundEndpoint: 'OMS'
